<div class="score11-rating-latest score11-listbox">
	<div class="title">Neue Wertungen</div>
	<div class="mini-preview">
		<?php $miniPreviewMovie = $this->miniPreviewMovie['rating-latest']; ?>
	    <?php if ($miniPreviewMovie['hasimage'] == 'y') { ?>
	    <a href="<?php print($miniPreviewMovie['movielink']); ?>">
			<img src="<?php print($miniPreviewMovie['image']); ?>" alt="" />
		</a>
		<?php } ?>
		<a href="<?php print($miniPreviewMovie['movielink']); ?>">
		    <?php print($miniPreviewMovie['movietitle']); ?>
	    </a><br />
		<span class="cast">
    		von <?php print($miniPreviewMovie['director']); ?>
    		mit <?php print($miniPreviewMovie['actor']); ?><br />
    		(<?php print($miniPreviewMovie['movieyear']); ?>)
		</span>
	</div>
	<div class="innerbox">
	<?php
	foreach($this->latestRatings as $key => $movie) {
        $rowClass = 'uneven-row';
        if ($key % 2 == 0) {
            $rowClass = 'even-row';
        }
    ?>
        <p class="movietitle <?php print($rowClass); ?>">
        	<span class="time">
        	    <?php print($movie['timestamp-time']); ?>
        	</span>
        	<span class="thumb">
        		<img src="<?php print($this->layout()->imgpath); ?>/thumb-<?php print($movie['thumb']); ?>" />
    		</span>
    		<span>
    			<a href="<?php print($movie['movielink']); ?>">
                    <?php print($movie['movietitle']); ?>
                </a>
                <?php print($movie['movieyear']); ?>
            </span>
            <br />
        </p>
	<?php } ?>
	</div>
</div>