<?php foreach ($this->comments as $comment) { ?>
<div class="score11-movie-comment">
	<div class="author">
		<a href="http://www.gravatar.com" class="gravatar"><img src="<?php print $comment['gravatar']; ?>" alt="" /></a>
		<?php if ($comment['showrating'] && !empty($comment['score'])) { ?>
		<span class="user-rating">
			<?php print $comment['score']; ?>/10
			<img src="<?php print $this->layout()->imgpath; ?>/<?php print $comment['thumb']; ?>" alt="<?php print $comment['score']; ?>" class="thumb" title="Wertung: <?php print $comment['score']; ?>" />
		</span>
		<?php } ?>
		<span class="name"><?php print $comment['username']; ?></span>
		<span class="timestamp">
			<?php print $comment['timestamp']; ?>
		</span>
	</div>
	<div class="text">
		<?php print $comment['text']; ?>
	</div>
</div>
<?php } ?>