<?php foreach ($this->comments as $comment) { ?>
<div class="score11-movie-comment">
	<div class="author">
		<a href="http://www.gravatar.com" class="gravatar"><img src="<?php print $comment['gravatar']; ?>" alt="" /></a>
		<span class="name"><?php print $comment['username']; ?></span>
		<span class="timestamp"><?php print $comment['timestamp']; ?></span>
	</div>
	<div class="text">
		<?php print $comment['text']; ?>
	</div>
</div>
<?php } ?>