<div class="score11-movie">
	<img src="<?php print $this->movie['image']; ?>" alt="" class="score11-movie-image" />
	<h1><?php print $this->movie['ori-title']['show-title']?></h1>
	<?php foreach ($this->movie['titles'] as $title) { ?>
		<?php if ($title['ID'] != $this->movie['ori']) { ?>
		<h2><?php print $title['show-title']?></h2>
		<?php } ?>
	<?php } ?>
	<div class="score11-separator score11-mobile-landscape">&nbsp;</div>
	
	<div class="score11-movie-ratings">
		<p class="score11-movie-rating-avg">
			<?php if($this->movie['ratings'] == 0) { ?>
			-
			<?php } else { ?>
			<?php print $this->movie['ratingsavg']; ?><span class="score11-rating-maximum">/ 10</span>
			<?php } ?>
		</p>
		<p>
			(<?php print $this->movie['ratings']; ?> Wertungen)
		</p>
	</div>
	
	<div class="score11-movie-info">
		<p class="basic-info score11-mobile-landscape">
			von <?php print $this->movie['regie']; ?>,
			mit <?php print $this->movie['actor']; ?><br />
			<a href="#">[Kompletten Cast anzeigen]</a>
		</p>
		<table>
			<tr>
				<td class="category">Genre</td>
				<td class="cast">
					<?php foreach ($this->movie['genres'] as $genre) { ?>
					<?php print($genre['DE']); ?> /
					<?php } ?>
				</td>
			</tr>
			<?php $castCounter = 0; $visibilityClass = ''; ?>
			<?php foreach ($this->movie['cast'] as $role => $castList) { ?>
			<?php if ($castCounter >= $this->maxCast) $visibilityClass = 'hidden'; ?>
			<tr class="<?php print $visibilityClass; ?>">
				<td class="category"><?php print $role; ?></td>
				<td class="cast">
					<?php foreach ($castList as $cast) { ?>
						<?php if ($castCounter >= $this->maxCast) $visibilityClass = 'hidden'; ?>
						<p class="<?php print $visibilityClass; ?>">
							<span class="name"><?php print($cast['name']); ?></span>
							<?php if (!empty($cast['role'])) { ?>
								<span class="role">... <?php print($cast['role']); ?></span>
							<?php } ?>
						</p>
						<?php $castCounter++; ?>
					<?php } ?>
				</td>
			</tr>
			<?php } ?>
			<?php if ($visibilityClass == 'hidden') { ?>
			<tr>
				<td>&nbsp;</td>
				<td><a href="#" id="score11-movie-info-showall">[Alle Eintr&auml;ge anzeigen]</a></td>
			</tr>
			<?php } ?>
			<tr>
				<td class="category">Agent</td>
				<td class="cast"><?php print($this->movie['agent']['name']); ?></td>
			</tr>
		</table>
	</div>
	
	<div class="score11-separator">&nbsp;</div>
	<script type="text/javascript">
		$('#score11-movie-info-showall').infotoggle({
			elements: '.score11-movie-info .hidden'
		});
	
		$('.score11-movie-info .basic-info a').infotoggle({
			elements: '.score11-movie-info table',
			hideAdditionally: '.score11-movie-info .basic-info'
		});
	</script>
	
	<div class="score11-movie-comments">
	</div>
	<script type="text/javascript">
		$('.score11-movie-comments').load('<?php print $this->commentsLink; ?>');
	</script>
</div>