<div class="score11-movie">
	<img src="<?php print $this->movie['image']; ?>" alt="" class="score11-movie-image" />
	<h1><?php print $this->movie['ori-title']['show-title']?></h1>
	<?php foreach ($this->movie['titles'] as $title) { ?>
		<?php if ($title['ID'] != $this->movie['ori']) { ?>
		<h2><?php print $title['show-title']?></h2>
		<?php } ?>
	<?php } ?>
	
	<div class="score11-movie-ratings">
	</div>
	<div class="score11-movie-infos">
		<table class="score11-movie-infos">
			<tr>
				<td class="category">Genre</td>
				<td class="cast">
					<?php foreach ($this->movie['genres'] as $genre) { ?>
					<?php print($genre['DE']); ?>
					<?php } ?>
				</td>
			</tr>
			<?php foreach ($this->movie['cast'] as $role => $castList) { ?>
			<tr>
				<td class="category"><?php print $role; ?></td>
				<td class="cast">
					<?php foreach ($castList as $cast) { ?>
						<span class="name"><?php print($cast['name']); ?></span>
						<?php if (!empty($cast['role'])) { ?>
							... <span class="role"><?php print($cast['role']); ?></span>
						<?php } ?>
						<br />
					<?php } ?>
				</td>
			</tr>
			<?php } ?>
			<tr>
				<td class="category">Agent</td>
				<td class="cast"><?php print($this->movie['agent']['name']); ?></td>
			</tr>
		</table>
	</div>
</div>