<div class="score11-ontv-home score11-listbox">
	<div class="title">Filmstarts</div>
	<?php if (!empty($this->movieStartlist)) { ?>
	<div class="mini-preview">
		<?php $miniPreviewMovie = $this->miniPreviewMovie['list-moviestart']; ?>
	    <?php if ($miniPreviewMovie['hasimage'] == 'y') { ?>
	    <a href="<?php print($miniPreviewMovie['movielink']); ?>">
			<img src="<?php print($miniPreviewMovie['image']); ?>" alt="" />
		</a>
		<?php } ?>
		<a href="<?php print($miniPreviewMovie['movielink']); ?>">
		    <?php print($miniPreviewMovie['movietitle']); ?>
	    </a><br />
		<span class="cast">
    		von <?php print($miniPreviewMovie['director']); ?>
    		mit <?php print($miniPreviewMovie['actor']); ?><br />
    		(<?php print($miniPreviewMovie['movieyear']); ?>)
		</span>
	</div>
	<?php foreach($this->movieStartlist as $date) { ?>
	<div class="innerbox">
		<p class="date uneven-row">
        	<?php print($date['date']); ?>
        </p>
        <?php
        foreach ($date['movies'] as $key => $movie) {
            $rowClass = 'uneven-row';
            if ($key % 2 == 0) {
                $rowClass = 'even-row';
            }
        ?>
        <p class="movietitle <?php print($rowClass); ?>">
        	<span class="thumb">
        		<img src="<?php print($this->layout()->imgpath); ?>/thumb-<?php print($movie['thumb']); ?>" />
    		</span>
    		<span>
    			<a href="<?php print($movie['movielink']); ?>">
                    <?php print($movie['movietitle']); ?>
                </a>
                <?php print($movie['movieyear']); ?>
            </span>
            <br />
        </p>
        <?php } ?>
	</div>
	<?php } ?>
	<?php } else { ?>
	<div class="uneven-row">
    	Derzeit gibt es keine Filmstarts.
    </div>
	<?php } ?>
</div>