<div class="score11-movie-imagelist score11-listbox">
	<div class="title"><?php echo $this->sectionTitle; ?></div>
	<?php if (!empty($this->movies)) { ?>
	<div>
	<?php foreach($this->movies as $key => $movie) { ?>
		<div class="mini-preview">
			<?php if ($movie['hasimage'] == 'n') $movie['image'] = 'img/logo-movie.png'; ?>
			<a class="score11-movie-no<?php print($key); ?>" href="<?php print($movie['movielink']); ?>" style="background: url(<?php print($movie['image']); ?>) no-repeat 50%;">
				<?php if (isset($movie['show-title']) && !empty($movie['show-title'])) { ?>
				<span class="movie-logo-overlay">
					<?php print($movie['show-title']); ?>
				</span>
				<?php } ?>
			</a>
			<a href="<?php print($movie['movielink']); ?>" class="movie-link">
			    <?php print($movie['movietitle']); ?>
		    </a>
		</div>
	<?php } ?>
	</div>
	<?php } ?>
</div>
