<div class="score11-home-left">
	<?php echo $this->render('modules/comment/latest.phtml'); ?>
	<?php echo $this->render('modules/rating/latest.phtml'); ?>
</div>
<div class="score11-home-right">
    <?php
	$this->movies = $this->onTv;
	$this->sectionTitle = 'Fernseh-Tipps';
	echo $this->render('modules/movieImageList.phtml');
    ?>
    <?php
	$this->movies = $this->movieStartlist;
	$this->sectionTitle = 'Filmstarts';
	echo $this->render('modules/movieImageList.phtml');
    ?>
</div>
