<!DOCTYPE html>
<html>
	<head>
		<base href="<?php print $this->layout()->urlbase; ?>" />
		<title><?php print $this->layout()->title; ?></title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    	<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport" />
    	<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/normalize.css" media="all" />		
		<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/layout.css" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/home.css" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/comment/latest.css" media="all" />
		<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/ontv/home.css" media="all" />
	</head>
	<body>
	<div class="score11-header">
		<div class="score11-celluloid">&nbsp;</div>
		<div class="logo">
			<p class="left">
				<img src="<?php print $this->layout()->imgpath; ?>/score11.gif" />
			</p>
			<p class="right">
				<span class="subtitle">The Movie Community</span>
			</p>
		</div>
		<div class="score11-celluloid">&nbsp;</div>
	</div>
	<div class="score11-separator">&nbsp;</div>
	
		<div class="score11-navigation">Here be navigation</div>
		<div class="score11-content"><?php print $this->layout()->content; ?></div>
		<div class="score11-sidebar">Here be sidebar</div>
	
	<div class="score11-separator">&nbsp;</div>
	<div class="score11-footer">
		<div class="score11-celluloid">&nbsp;</div>
		<div class="score11-copyright">
			<span class="base-copyright">Copyright &copy; 2000 - 2011 Stefan Schwarz &amp; Dominik Jungowski. Alle Rechte vorbehalten.</span>
			<br />
			<span class="extended-copyright">Bitte beachten Sie die Rechtshinweise, die Nutzungsbedingungen und die Nettiquette.</span>
			<br />
			<span class="domains">score11.de - sc11.de - sc11.com - score11.com</span>
		</div>
	</div>
	<script type="text/javascript" href="<?php print $this->layout()->urlbase; ?>js/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" href="<?php print $this->layout()->urlbase; ?>js/hideAdressbar.js"></script>
	</body>
</html>