<!DOCTYPE html>
<html>
	<head>
		<base href="<?php print $this->layout()->urlbase; ?>" />
		<title><?php print $this->layout()->title; ?></title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    	<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport" />
    	<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/normalize.css" media="all" />		
		<link rel="stylesheet" type="text/css" href="<?php print $this->layout()->urlbase; ?>css/layout.css" media="all" />
	</head>
	<body>
	<div class="score11-header">
		<div class="celluloid">&nbsp;</div>
		<div class="logo">
			<p class="left">
				<img src="<?php print $this->layout()->imgpath; ?>/score11.gif" />
			</p>
			<p class="right">
				<span class="subtitle">The Movie Community</span>
			</p>
		</div>
		<div class="celluloid">&nbsp;</div>
	</div>
	<script type="text/javascript" href="<?php print $this->layout()->urlbase; ?>js/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" href="<?php print $this->layout()->urlbase; ?>js/jquery/plugins/jquery.smartresize.js"></script>
	<script type="text/javascript" href="<?php print $this->layout()->urlbase; ?>js/hideAdressbar.js"></script>
	</body>
</html>