<div class="score11-ontv-home score11-listbox">
	<div class="title">Fernseh-Tipps</div>
	<?php if (!empty($this->onTv)) { ?>
	<div>
	<?php foreach($this->onTv as $date) { ?>
        <?php foreach ($date['movies'] as $key => $movie) { ?>
		<a href="<?php print($movie['movielink']); ?>" style="background: url(<?php print($movie['image']); ?>) no-repeat 50%;">
			<span>
				<?php print($movie['timestamp-time']); ?><br />
			    	<?php print($movie['sender']); ?><br />
				<?php print($movie['movietitle']); ?>
			</span>
		</a>
	<?php } ?>
	<?php } ?>
	</div>
	<?php } else { ?>
	<div class="uneven-row">
    	Derzeit gibt es keinen Fernsehtipps.
    </div>
	<?php } ?>
</div>
