<div class="score11-ontv-home score11-listbox">
	<div class="title">Fernseh-Tipps</div>
	<?php if (!empty($this->onTv)) { ?>
	<div>
	<?php foreach($this->onTv as $date) { ?>
        <?php foreach ($date['movies'] as $key => $movie) { ?>
		<p style="background: url(<?php print($movie['image']); ?>) no-repeat 50%;">
			<span><?php print($movie['movietitle']); ?></span>
		</p>
	<?php } ?>
	<?php } ?>
	</div>
	<?php } else { ?>
	<div class="uneven-row">
    	Derzeit gibt es keinen Fernsehtipps.
    </div>
	<?php } ?>
</div>
