<div class="score11-comment-latest score11-listbox">
	<div class="title">Neue Kommentare</div>
	<div class="mini-preview">
		<img src="http://www.score11.de/p/29/40529" />
		<?php print($this->miniPreviewMovie['movietitle']); ?><br />
		<span class="cast">
    		von <?php print($this->miniPreviewMovie['director']); ?>
    		mit <?php print($this->miniPreviewMovie['actor']); ?><br />
    		(<?php print($this->miniPreviewMovie['movieyear']); ?>)
		</span>
		<?php if ($this->miniPreviewMovie['image'] == 'y') { } ?>
	</div>
    <?php foreach($this->latestComments as $comment) { ?>
    <div class="innerbox">
        <p class="date uneven-row">
        	<?php print($comment['timestamp-day']); ?>
        </p>
        <p class="movietitle even-row">
        	<span>
        	    <?php print($comment['timestamp-time']); ?>
        	</span>
        	<span class="thumb">
        		<img src="<?php print($this->layout()->imgpath); ?>/thumb-<?php print($comment['thumb']); ?>" />
    		</span>
    		<span>
                <?php print($comment['movietitle']); ?>
                <?php print($comment['movieyear']); ?>
            </span>
            <br />
            Kommentar von <?php print($comment['user']); ?>
        </p>
        <p class="comment uneven-row">
        	<?php print($comment['text_shortened']); ?>
        </p>
    </div>
    <?php } ?>
</div>