<div class="score11-comment-latest score11-listbox">
	<div class="title">Neue Kommentare</div>
	<div class="mini-preview">
	    <?php if ($this->miniPreviewMovie['hasimage'] == 'y') { ?>
	    <a href="<?php print($this->miniPreviewMovie['movielink']); ?>">
			<img src="<?php print($this->miniPreviewMovie['image']); ?>" alt="" />
		</a>
		<?php } ?>
		<a href="<?php print($this->miniPreviewMovie['movielink']); ?>">
		    <?php print($this->miniPreviewMovie['movietitle']); ?>
	    </a><br />
		<span class="cast">
    		von <?php print($this->miniPreviewMovie['director']); ?>
    		mit <?php print($this->miniPreviewMovie['actor']); ?><br />
    		(<?php print($this->miniPreviewMovie['movieyear']); ?>)
		</span>
	</div>
    <?php foreach($this->latestComments as $comment) { ?>
    <div class="innerbox">
        <p class="date uneven-row">
        	<?php print($comment['timestamp-day']); ?>
        </p>
        <p class="movietitle even-row">
        	<span>
        	    <?php print($comment['timestamp-time']); ?>
        	</span>
        	<span class="thumb">
        		<img src="<?php print($this->layout()->imgpath); ?>/thumb-<?php print($comment['thumb']); ?>" />
    		</span>
    		<span>
    			<a href="<?php print($comment['movielink']); ?>">
                    <?php print($comment['movietitle']); ?>
                </a>
                <?php print($comment['movieyear']); ?>
            </span>
            <br />
            Kommentar von <?php print($comment['user']); ?>
        </p>
        <p class="comment uneven-row">
        	<?php print($comment['text_shortened']); ?>
        </p>
    </div>
    <?php } ?>
</div>